### ISSUE TITLE
Roundcube login does not work if we remove the role roundcube from idp

### ISSUE THREAD

**Issue by ganesh-at-wiw** [GluuFederation/roundcube-oxd-plugin#8]
Roundcube login does not work if we remove the role roundcube from idp. This behaviour is in conflict with the solution you've presented for suitecrm. Either suitecrm login should also stop after removing the role from idp or roundcube login should also work after removing the role from idp.

**Comment by willow9886** [comment]
If the role is removed, the user should not be able to login any longer. This seems like the correct behavior, and SuiteCRM seems like incorrect behavior.
